'use strict'

Object.defineProperty(exports, '__esModule', {
    value: true
})

const _createClass = (function() { function defineProperties(target, props) { for (let i = 0; i < props.length; i++) { const descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ('value' in descriptor) { descriptor.writable = true } Object.defineProperty(target, descriptor.key, descriptor) } } return function(Constructor, protoProps, staticProps) { if (protoProps) { defineProperties(Constructor.prototype, protoProps) } if (staticProps) { defineProperties(Constructor, staticProps) } return Constructor } }()) /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */


const _ApiClient = require('../ApiClient')

const _ApiClient2 = _interopRequireDefault(_ApiClient)

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : {default: obj} }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function') } }

/**
* The CustomerProductListItemLinkModel model module.
* @module models/CustomerProductListItemLinkModel
* @version 17.8
*/
const CustomerProductListItemLinkModel = (function() {
    /**
    * Constructs a new <code>CustomerProductListItemLinkModel</code>.
    * Document representing a customer product list item link.
    * @alias module:models/CustomerProductListItemLinkModel
    * @class
    */
    function CustomerProductListItemLinkModel() {
        _classCallCheck(this, CustomerProductListItemLinkModel)

        this.link = undefined
        this.title = undefined
    }

    /**
    * Constructs a <code>CustomerProductListItemLinkModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CustomerProductListItemLinkModel} obj Optional instance to populate.
    * @return {module:models/CustomerProductListItemLinkModel} The populated <code>CustomerProductListItemLinkModel</code> instance.
    */


    _createClass(CustomerProductListItemLinkModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new CustomerProductListItemLinkModel()

                if (data.hasOwnProperty('link')) {
                    obj.link = _ApiClient2.default.convertToType(data.link, 'String')
                }
                if (data.hasOwnProperty('title')) {
                    obj.title = _ApiClient2.default.convertToType(data.title, 'String')
                }
            }

            return obj
        }

        /**
        * The target of the link.
        * @member {String} link
        */

        /**
        * The link title.
        * @member {String} title
        */

    }])

    return CustomerProductListItemLinkModel
}())

exports.default = CustomerProductListItemLinkModel
