'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _CustomerAddressModel = require('./CustomerAddressModel');

var _CustomerAddressModel2 = _interopRequireDefault(_CustomerAddressModel);

var _CustomerPaymentInstrumentModel = require('./CustomerPaymentInstrumentModel');

var _CustomerPaymentInstrumentModel2 = _interopRequireDefault(_CustomerPaymentInstrumentModel);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The CustomerModel model module.
* @module models/CustomerModel
* @version 17.8
*/
var CustomerModel = function () {
    /**
    * Constructs a new <code>CustomerModel</code>.
    * Document representing a customer.
    * @alias module:models/CustomerModel
    * @class
    */

    function CustomerModel() {
        _classCallCheck(this, CustomerModel);

        this.addresses = undefined;
        this.auth_type = undefined;
        this.birthday = undefined;
        this.c_familyStatus = undefined;
        this.company_name = undefined;
        this.creation_date = undefined;
        this.customer_id = undefined;
        this.customer_no = undefined;
        this.email = undefined;
        this.enabled = undefined;
        this.fax = undefined;
        this.first_name = undefined;
        this.gender = undefined;
        this.job_title = undefined;
        this.last_login_time = undefined;
        this.last_modified = undefined;
        this.last_name = undefined;
        this.last_visit_time = undefined;
        this.login = undefined;
        this.note = undefined;
        this.payment_instruments = undefined;
        this.phone_business = undefined;
        this.phone_home = undefined;
        this.phone_mobile = undefined;
        this.preferred_locale = undefined;
        this.previous_login_time = undefined;
        this.previous_visit_time = undefined;
        this.salutation = undefined;
        this.second_name = undefined;
        this.suffix = undefined;
        this.title = undefined;
    }

    /**
    * Constructs a <code>CustomerModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CustomerModel} obj Optional instance to populate.
    * @return {module:models/CustomerModel} The populated <code>CustomerModel</code> instance.
    */


    _createClass(CustomerModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new CustomerModel();

                if (data.hasOwnProperty('addresses')) {
                    obj['addresses'] = _ApiClient2.default.convertToType(data['addresses'], [_CustomerAddressModel2.default]);
                }
                if (data.hasOwnProperty('auth_type')) {
                    obj['auth_type'] = _ApiClient2.default.convertToType(data['auth_type'], 'String');
                }
                if (data.hasOwnProperty('birthday')) {
                    obj['birthday'] = _ApiClient2.default.convertToType(data['birthday'], 'Date');
                }
                if (data.hasOwnProperty('c_familyStatus')) {
                    obj['c_familyStatus'] = _ApiClient2.default.convertToType(data['c_familyStatus'], 'String');
                }
                if (data.hasOwnProperty('company_name')) {
                    obj['company_name'] = _ApiClient2.default.convertToType(data['company_name'], 'String');
                }
                if (data.hasOwnProperty('creation_date')) {
                    obj['creation_date'] = _ApiClient2.default.convertToType(data['creation_date'], 'Date');
                }
                if (data.hasOwnProperty('customer_id')) {
                    obj['customer_id'] = _ApiClient2.default.convertToType(data['customer_id'], 'String');
                }
                if (data.hasOwnProperty('customer_no')) {
                    obj['customer_no'] = _ApiClient2.default.convertToType(data['customer_no'], 'String');
                }
                if (data.hasOwnProperty('email')) {
                    obj['email'] = _ApiClient2.default.convertToType(data['email'], 'String');
                }
                if (data.hasOwnProperty('enabled')) {
                    obj['enabled'] = _ApiClient2.default.convertToType(data['enabled'], 'Boolean');
                }
                if (data.hasOwnProperty('fax')) {
                    obj['fax'] = _ApiClient2.default.convertToType(data['fax'], 'String');
                }
                if (data.hasOwnProperty('first_name')) {
                    obj['first_name'] = _ApiClient2.default.convertToType(data['first_name'], 'String');
                }
                if (data.hasOwnProperty('gender')) {
                    obj['gender'] = _ApiClient2.default.convertToType(data['gender'], 'Number');
                }
                if (data.hasOwnProperty('job_title')) {
                    obj['job_title'] = _ApiClient2.default.convertToType(data['job_title'], 'String');
                }
                if (data.hasOwnProperty('last_login_time')) {
                    obj['last_login_time'] = _ApiClient2.default.convertToType(data['last_login_time'], 'Date');
                }
                if (data.hasOwnProperty('last_modified')) {
                    obj['last_modified'] = _ApiClient2.default.convertToType(data['last_modified'], 'Date');
                }
                if (data.hasOwnProperty('last_name')) {
                    obj['last_name'] = _ApiClient2.default.convertToType(data['last_name'], 'String');
                }
                if (data.hasOwnProperty('last_visit_time')) {
                    obj['last_visit_time'] = _ApiClient2.default.convertToType(data['last_visit_time'], 'Date');
                }
                if (data.hasOwnProperty('login')) {
                    obj['login'] = _ApiClient2.default.convertToType(data['login'], 'String');
                }
                if (data.hasOwnProperty('note')) {
                    obj['note'] = _ApiClient2.default.convertToType(data['note'], 'String');
                }
                if (data.hasOwnProperty('payment_instruments')) {
                    obj['payment_instruments'] = _ApiClient2.default.convertToType(data['payment_instruments'], [_CustomerPaymentInstrumentModel2.default]);
                }
                if (data.hasOwnProperty('phone_business')) {
                    obj['phone_business'] = _ApiClient2.default.convertToType(data['phone_business'], 'String');
                }
                if (data.hasOwnProperty('phone_home')) {
                    obj['phone_home'] = _ApiClient2.default.convertToType(data['phone_home'], 'String');
                }
                if (data.hasOwnProperty('phone_mobile')) {
                    obj['phone_mobile'] = _ApiClient2.default.convertToType(data['phone_mobile'], 'String');
                }
                if (data.hasOwnProperty('preferred_locale')) {
                    obj['preferred_locale'] = _ApiClient2.default.convertToType(data['preferred_locale'], 'String');
                }
                if (data.hasOwnProperty('previous_login_time')) {
                    obj['previous_login_time'] = _ApiClient2.default.convertToType(data['previous_login_time'], 'Date');
                }
                if (data.hasOwnProperty('previous_visit_time')) {
                    obj['previous_visit_time'] = _ApiClient2.default.convertToType(data['previous_visit_time'], 'Date');
                }
                if (data.hasOwnProperty('salutation')) {
                    obj['salutation'] = _ApiClient2.default.convertToType(data['salutation'], 'String');
                }
                if (data.hasOwnProperty('second_name')) {
                    obj['second_name'] = _ApiClient2.default.convertToType(data['second_name'], 'String');
                }
                if (data.hasOwnProperty('suffix')) {
                    obj['suffix'] = _ApiClient2.default.convertToType(data['suffix'], 'String');
                }
                if (data.hasOwnProperty('title')) {
                    obj['title'] = _ApiClient2.default.convertToType(data['title'], 'String');
                }
            }
            return obj;
        }

        /**
        * The customer's addresses.
        * @member {Array.<module:models/CustomerAddressModel>} addresses
        */

        /**
        * The customer's authorization type (indicates if the customer is a guest  or a registered customer).
        * @member {module:models/CustomerModel.AuthTypeEnum} auth_type
        */

        /**
        * The customer's birthday.
        * @member {Date} birthday
        */

        /**
        * @member {String} c_familyStatus
        */

        /**
        * The customer's company name.
        * @member {String} company_name
        */

        /**
        * Returns the value of attribute 'creationDate'.
        * @member {Date} creation_date
        */

        /**
        * The customer's number (id). Both registered and guest customers have a  customer id.
        * @member {String} customer_id
        */

        /**
        * The customer's number (id). Only a registered customer has a customer  number.
        * @member {String} customer_no
        */

        /**
        * The customer's email address.
        * @member {String} email
        */

        /**
        * A flag indicating whether this customer is is enabled and can log in.
        * @member {Boolean} enabled
        */

        /**
        * The customer's fax number. The length is restricted to 32 characters.
        * @member {String} fax
        */

        /**
        * The customer's first name.
        * @member {String} first_name
        */

        /**
        * The customer's gender.
        * @member {module:models/CustomerModel.GenderEnum} gender
        */

        /**
        * The customer's job title.
        * @member {String} job_title
        */

        /**
        * The time when the customer last logged in.
        * @member {Date} last_login_time
        */

        /**
        * Returns the value of attribute 'lastModified'.
        * @member {Date} last_modified
        */

        /**
        * The customer's last name.
        * @member {String} last_name
        */

        /**
        * The time when the customer last visited.
        * @member {Date} last_visit_time
        */

        /**
        * The customer's login.
        * @member {String} login
        */

        /**
        * The customer's note.
        * @member {String} note
        */

        /**
        * The customer's payment instruments.
        * @member {Array.<module:models/CustomerPaymentInstrumentModel>} payment_instruments
        */

        /**
        * The customer's business phone number.
        * @member {String} phone_business
        */

        /**
        * The customer's home phone number.
        * @member {String} phone_home
        */

        /**
        * The customer's mobile phone number.
        * @member {String} phone_mobile
        */

        /**
        * The customer's preferred locale.
        * @member {String} preferred_locale
        */

        /**
        * The time when the customer logged in previously.
        * @member {Date} previous_login_time
        */

        /**
        * The time when the customer last visited the store.
        * @member {Date} previous_visit_time
        */

        /**
        * The salutation to use for the customer.
        * @member {String} salutation
        */

        /**
        * The customer's second name.
        * @member {String} second_name
        */

        /**
        * The customer's suffix (for example, \"Jr.\" or \"Sr.\").
        * @member {String} suffix
        */

        /**
        * The customer's title (for example, \"Mrs\" or \"Mr\").
        * @member {String} title
        */


        /**
        * Allowed values for the <code>auth_type</code> property.
        * @enum {String}
        * @readonly
        */


        /**
        * Allowed values for the <code>gender</code> property.
        * @enum {Number}
        * @readonly
        */

    }]);

    return CustomerModel;
}();

CustomerModel.AuthTypeEnum = {

    /**
     * value: "guest"
     * @const
     */
    "guest": "guest",

    /**
     * value: "registered"
     * @const
     */
    "registered": "registered"
};
CustomerModel.GenderEnum = {

    /**
     * value: 1
     * @const
     */
    "1": 1,

    /**
     * value: 2
     * @const
     */
    "2": 2
};
exports.default = CustomerModel;