'use strict'

Object.defineProperty(exports, '__esModule', {
    value: true
})

const _createClass = (function() { function defineProperties(target, props) { for (let i = 0; i < props.length; i++) { const descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ('value' in descriptor) { descriptor.writable = true } Object.defineProperty(target, descriptor.key, descriptor) } } return function(Constructor, protoProps, staticProps) { if (protoProps) { defineProperties(Constructor.prototype, protoProps) } if (staticProps) { defineProperties(Constructor, staticProps) } return Constructor } }()) /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */


const _ApiClient = require('../ApiClient')

const _ApiClient2 = _interopRequireDefault(_ApiClient)

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : {default: obj} }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function') } }

/**
* The CustomerAddressModel model module.
* @module models/CustomerAddressModel
* @version 17.8
*/
const CustomerAddressModel = (function() {
    /**
    * Constructs a new <code>CustomerAddressModel</code>.
    * Document representing a customer address.
    * @alias module:models/CustomerAddressModel
    * @class
    */
    function CustomerAddressModel() {
        _classCallCheck(this, CustomerAddressModel)

        this.address1 = undefined
        this.address2 = undefined
        this.address_id = undefined
        this.city = undefined
        this.company_name = undefined
        this.country_code = undefined
        this.creation_date = undefined
        this.first_name = undefined
        this.full_name = undefined
        this.job_title = undefined
        this.last_modified = undefined
        this.last_name = undefined
        this.phone = undefined
        this.post_box = undefined
        this.postal_code = undefined
        this.preferred = undefined
        this.salutation = undefined
        this.second_name = undefined
        this.state_code = undefined
        this.suffix = undefined
        this.suite = undefined
        this.title = undefined
    }

    /**
    * Constructs a <code>CustomerAddressModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CustomerAddressModel} obj Optional instance to populate.
    * @return {module:models/CustomerAddressModel} The populated <code>CustomerAddressModel</code> instance.
    */


    _createClass(CustomerAddressModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new CustomerAddressModel()

                if (data.hasOwnProperty('address1')) {
                    obj.address1 = _ApiClient2.default.convertToType(data.address1, 'String')
                }
                if (data.hasOwnProperty('address2')) {
                    obj.address2 = _ApiClient2.default.convertToType(data.address2, 'String')
                }
                if (data.hasOwnProperty('address_id')) {
                    obj.address_id = _ApiClient2.default.convertToType(data.address_id, 'String')
                }
                if (data.hasOwnProperty('city')) {
                    obj.city = _ApiClient2.default.convertToType(data.city, 'String')
                }
                if (data.hasOwnProperty('company_name')) {
                    obj.company_name = _ApiClient2.default.convertToType(data.company_name, 'String')
                }
                if (data.hasOwnProperty('country_code')) {
                    obj.country_code = _ApiClient2.default.convertToType(data.country_code, 'String')
                }
                if (data.hasOwnProperty('creation_date')) {
                    obj.creation_date = _ApiClient2.default.convertToType(data.creation_date, 'Date')
                }
                if (data.hasOwnProperty('first_name')) {
                    obj.first_name = _ApiClient2.default.convertToType(data.first_name, 'String')
                }
                if (data.hasOwnProperty('full_name')) {
                    obj.full_name = _ApiClient2.default.convertToType(data.full_name, 'String')
                }
                if (data.hasOwnProperty('job_title')) {
                    obj.job_title = _ApiClient2.default.convertToType(data.job_title, 'String')
                }
                if (data.hasOwnProperty('last_modified')) {
                    obj.last_modified = _ApiClient2.default.convertToType(data.last_modified, 'Date')
                }
                if (data.hasOwnProperty('last_name')) {
                    obj.last_name = _ApiClient2.default.convertToType(data.last_name, 'String')
                }
                if (data.hasOwnProperty('phone')) {
                    obj.phone = _ApiClient2.default.convertToType(data.phone, 'String')
                }
                if (data.hasOwnProperty('post_box')) {
                    obj.post_box = _ApiClient2.default.convertToType(data.post_box, 'String')
                }
                if (data.hasOwnProperty('postal_code')) {
                    obj.postal_code = _ApiClient2.default.convertToType(data.postal_code, 'String')
                }
                if (data.hasOwnProperty('preferred')) {
                    obj.preferred = _ApiClient2.default.convertToType(data.preferred, 'Boolean')
                }
                if (data.hasOwnProperty('salutation')) {
                    obj.salutation = _ApiClient2.default.convertToType(data.salutation, 'String')
                }
                if (data.hasOwnProperty('second_name')) {
                    obj.second_name = _ApiClient2.default.convertToType(data.second_name, 'String')
                }
                if (data.hasOwnProperty('state_code')) {
                    obj.state_code = _ApiClient2.default.convertToType(data.state_code, 'String')
                }
                if (data.hasOwnProperty('suffix')) {
                    obj.suffix = _ApiClient2.default.convertToType(data.suffix, 'String')
                }
                if (data.hasOwnProperty('suite')) {
                    obj.suite = _ApiClient2.default.convertToType(data.suite, 'String')
                }
                if (data.hasOwnProperty('title')) {
                    obj.title = _ApiClient2.default.convertToType(data.title, 'String')
                }
            }

            return obj
        }

        /**
        * The first address.
        * @member {String} address1
        */

        /**
        * The second address.
        * @member {String} address2
        */

        /**
        * The id of the address as specified by account owner.
        * @member {String} address_id
        */

        /**
        * The city.
        * @member {String} city
        */

        /**
        * The company name.
        * @member {String} company_name
        */

        /**
        * The two-letter ISO 3166-1 (Alpha-2) country code.
        * @member {module:models/CustomerAddressModel.CountryCodeEnum} country_code
        */

        /**
        * Returns the value of attribute 'creationDate'.
        * @member {Date} creation_date
        */

        /**
        * The first name.
        * @member {String} first_name
        */

        /**
        * The full name.
        * @member {String} full_name
        */

        /**
        * The job title.
        * @member {String} job_title
        */

        /**
        * Returns the value of attribute 'lastModified'.
        * @member {Date} last_modified
        */

        /**
        * The last name.
        * @member {String} last_name
        */

        /**
        * The phone number.
        * @member {String} phone
        */

        /**
        * The post box.
        * @member {String} post_box
        */

        /**
        * The postal code.
        * @member {String} postal_code
        */

        /**
        * The preferred attribute.
        * @member {Boolean} preferred
        */

        /**
        * The salutation.
        * @member {String} salutation
        */

        /**
        * The second name.
        * @member {String} second_name
        */

        /**
        * The state code.
        * @member {String} state_code
        */

        /**
        * The suffix.
        * @member {String} suffix
        */

        /**
        * The suite.
        * @member {String} suite
        */

        /**
        * The title.
        * @member {String} title
        */


        /**
        * Allowed values for the <code>country_code</code> property.
        * @enum {String}
        * @readonly
        */

    }])

    return CustomerAddressModel
}())

CustomerAddressModel.CountryCodeEnum = {

    /**
     * value: "US"
     * @const
     */
    US: 'US',

    /**
     * value: "FR"
     * @const
     */
    FR: 'FR',

    /**
     * value: "IT"
     * @const
     */
    IT: 'IT',

    /**
     * value: "JP"
     * @const
     */
    JP: 'JP',

    /**
     * value: "CN"
     * @const
     */
    CN: 'CN',

    /**
     * value: "GB"
     * @const
     */
    GB: 'GB'
}
exports.default = CustomerAddressModel
