'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */


var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _CustomerPaymentCardRequestModel = require('./CustomerPaymentCardRequestModel');

var _CustomerPaymentCardRequestModel2 = _interopRequireDefault(_CustomerPaymentCardRequestModel);

var _PaymentBankAccountRequestModel = require('./PaymentBankAccountRequestModel');

var _PaymentBankAccountRequestModel2 = _interopRequireDefault(_PaymentBankAccountRequestModel);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The CustomerPaymentInstrumentRequestModel model module.
* @module models/CustomerPaymentInstrumentRequestModel
* @version 17.8
*/
var CustomerPaymentInstrumentRequestModel = function () {
    /**
    * Constructs a new <code>CustomerPaymentInstrumentRequestModel</code>.
    * Document representing a customer payment instrument request.
    * @alias module:models/CustomerPaymentInstrumentRequestModel
    * @class
    */
    function CustomerPaymentInstrumentRequestModel() {
        _classCallCheck(this, CustomerPaymentInstrumentRequestModel);

        this.bank_routing_number = undefined;
        this.gift_certificate_code = undefined;
        this.payment_bank_account = undefined;
        this.payment_card = undefined;
        this.payment_method_id = undefined;
    }

    /**
    * Constructs a <code>CustomerPaymentInstrumentRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CustomerPaymentInstrumentRequestModel} obj Optional instance to populate.
    * @return {module:models/CustomerPaymentInstrumentRequestModel} The populated <code>CustomerPaymentInstrumentRequestModel</code> instance.
    */


    _createClass(CustomerPaymentInstrumentRequestModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new CustomerPaymentInstrumentRequestModel();

                if (data.hasOwnProperty('bank_routing_number')) {
                    obj['bank_routing_number'] = _ApiClient2.default.convertToType(data['bank_routing_number'], 'String');
                }
                if (data.hasOwnProperty('gift_certificate_code')) {
                    obj['gift_certificate_code'] = _ApiClient2.default.convertToType(data['gift_certificate_code'], 'String');
                }
                if (data.hasOwnProperty('payment_bank_account')) {
                    obj['payment_bank_account'] = _PaymentBankAccountRequestModel2.default.constructFromObject(data['payment_bank_account']);
                }
                if (data.hasOwnProperty('payment_card')) {
                    obj['payment_card'] = _CustomerPaymentCardRequestModel2.default.constructFromObject(data['payment_card']);
                }
                if (data.hasOwnProperty('payment_method_id')) {
                    obj['payment_method_id'] = _ApiClient2.default.convertToType(data['payment_method_id'], 'String');
                }
            }

            return obj;
        }

        /**
        * The bank routing number.
        * @member {String} bank_routing_number
        */

        /**
        * The gift certificate code.
        * @member {String} gift_certificate_code
        */

        /**
        * The payment bank account request data.
        * @member {module:models/PaymentBankAccountRequestModel} payment_bank_account
        */

        /**
        * The customer payment card.
        * @member {module:models/CustomerPaymentCardRequestModel} payment_card
        */

        /**
        * The payment method id. Optional if a customer payment instrument id is specified.
        * @member {String} payment_method_id
        */

    }]);

    return CustomerPaymentInstrumentRequestModel;
}();

exports.default = CustomerPaymentInstrumentRequestModel;