'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _PaymentBankAccountModel = require('./PaymentBankAccountModel');

var _PaymentBankAccountModel2 = _interopRequireDefault(_PaymentBankAccountModel);

var _PaymentCardModel = require('./PaymentCardModel');

var _PaymentCardModel2 = _interopRequireDefault(_PaymentCardModel);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The CustomerPaymentInstrumentModel model module.
* @module models/CustomerPaymentInstrumentModel
* @version 17.8
*/
var CustomerPaymentInstrumentModel = function () {
    /**
    * Constructs a new <code>CustomerPaymentInstrumentModel</code>.
    * Document representing a customer payment instrument.
    * @alias module:models/CustomerPaymentInstrumentModel
    * @class
    */

    function CustomerPaymentInstrumentModel() {
        _classCallCheck(this, CustomerPaymentInstrumentModel);

        this.bank_routing_number = undefined;
        this.creation_date = undefined;
        this.last_modified = undefined;
        this.masked_gift_certificate_code = undefined;
        this.payment_bank_account = undefined;
        this.payment_card = undefined;
        this.payment_instrument_id = undefined;
        this.payment_method_id = undefined;
    }

    /**
    * Constructs a <code>CustomerPaymentInstrumentModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CustomerPaymentInstrumentModel} obj Optional instance to populate.
    * @return {module:models/CustomerPaymentInstrumentModel} The populated <code>CustomerPaymentInstrumentModel</code> instance.
    */


    _createClass(CustomerPaymentInstrumentModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new CustomerPaymentInstrumentModel();

                if (data.hasOwnProperty('bank_routing_number')) {
                    obj['bank_routing_number'] = _ApiClient2.default.convertToType(data['bank_routing_number'], 'String');
                }
                if (data.hasOwnProperty('creation_date')) {
                    obj['creation_date'] = _ApiClient2.default.convertToType(data['creation_date'], 'Date');
                }
                if (data.hasOwnProperty('last_modified')) {
                    obj['last_modified'] = _ApiClient2.default.convertToType(data['last_modified'], 'Date');
                }
                if (data.hasOwnProperty('masked_gift_certificate_code')) {
                    obj['masked_gift_certificate_code'] = _ApiClient2.default.convertToType(data['masked_gift_certificate_code'], 'String');
                }
                if (data.hasOwnProperty('payment_bank_account')) {
                    obj['payment_bank_account'] = _PaymentBankAccountModel2.default.constructFromObject(data['payment_bank_account']);
                }
                if (data.hasOwnProperty('payment_card')) {
                    obj['payment_card'] = _PaymentCardModel2.default.constructFromObject(data['payment_card']);
                }
                if (data.hasOwnProperty('payment_instrument_id')) {
                    obj['payment_instrument_id'] = _ApiClient2.default.convertToType(data['payment_instrument_id'], 'String');
                }
                if (data.hasOwnProperty('payment_method_id')) {
                    obj['payment_method_id'] = _ApiClient2.default.convertToType(data['payment_method_id'], 'String');
                }
            }
            return obj;
        }

        /**
        * The bank routing number.
        * @member {String} bank_routing_number
        */

        /**
        * Returns the value of attribute 'creationDate'.
        * @member {Date} creation_date
        */

        /**
        * Returns the value of attribute 'lastModified'.
        * @member {Date} last_modified
        */

        /**
        * The masked gift certificate code.
        * @member {String} masked_gift_certificate_code
        */

        /**
        * The payment bank account.
        * @member {module:models/PaymentBankAccountModel} payment_bank_account
        */

        /**
        * The payment card.
        * @member {module:models/PaymentCardModel} payment_card
        */

        /**
        * The payment instrument ID.
        * @member {String} payment_instrument_id
        */

        /**
        * The payment method id. Optional if a customer payment instrument id is specified.
        * @member {String} payment_method_id
        */

    }]);

    return CustomerPaymentInstrumentModel;
}();

exports.default = CustomerPaymentInstrumentModel;