'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The GiftCertificateModel model module.
* @module models/GiftCertificateModel
* @version 17.8
*/
var GiftCertificateModel = function () {
    /**
    * Constructs a new <code>GiftCertificateModel</code>.
    * Document representing a gift certificate.
    * @alias module:models/GiftCertificateModel
    * @class
    */

    function GiftCertificateModel() {
        _classCallCheck(this, GiftCertificateModel);

        this.amount = undefined;
        this.balance = undefined;
        this.description = undefined;
        this.enabled = undefined;
        this.masked_gift_certificate_code = undefined;
        this.merchant_id = undefined;
        this.message = undefined;
        this.recipient_email = undefined;
        this.recipient_name = undefined;
        this.sender_name = undefined;
        this.status = undefined;
    }

    /**
    * Constructs a <code>GiftCertificateModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/GiftCertificateModel} obj Optional instance to populate.
    * @return {module:models/GiftCertificateModel} The populated <code>GiftCertificateModel</code> instance.
    */


    _createClass(GiftCertificateModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new GiftCertificateModel();

                if (data.hasOwnProperty('amount')) {
                    obj['amount'] = _ApiClient2.default.convertToType(data['amount'], 'Number');
                }
                if (data.hasOwnProperty('balance')) {
                    obj['balance'] = _ApiClient2.default.convertToType(data['balance'], 'Number');
                }
                if (data.hasOwnProperty('description')) {
                    obj['description'] = _ApiClient2.default.convertToType(data['description'], 'String');
                }
                if (data.hasOwnProperty('enabled')) {
                    obj['enabled'] = _ApiClient2.default.convertToType(data['enabled'], 'Boolean');
                }
                if (data.hasOwnProperty('masked_gift_certificate_code')) {
                    obj['masked_gift_certificate_code'] = _ApiClient2.default.convertToType(data['masked_gift_certificate_code'], 'String');
                }
                if (data.hasOwnProperty('merchant_id')) {
                    obj['merchant_id'] = _ApiClient2.default.convertToType(data['merchant_id'], 'String');
                }
                if (data.hasOwnProperty('message')) {
                    obj['message'] = _ApiClient2.default.convertToType(data['message'], 'String');
                }
                if (data.hasOwnProperty('recipient_email')) {
                    obj['recipient_email'] = _ApiClient2.default.convertToType(data['recipient_email'], 'String');
                }
                if (data.hasOwnProperty('recipient_name')) {
                    obj['recipient_name'] = _ApiClient2.default.convertToType(data['recipient_name'], 'String');
                }
                if (data.hasOwnProperty('sender_name')) {
                    obj['sender_name'] = _ApiClient2.default.convertToType(data['sender_name'], 'String');
                }
                if (data.hasOwnProperty('status')) {
                    obj['status'] = _ApiClient2.default.convertToType(data['status'], 'String');
                }
            }
            return obj;
        }

        /**
        * The gift certificate original amount.
        * @member {Number} amount
        */

        /**
        * The gift certificate balance.
        * @member {Number} balance
        */

        /**
        * The gift certificate description.
        * @member {String} description
        */

        /**
        * Is the gift certificate is enabled?
        * @member {Boolean} enabled
        */

        /**
        * The masked gift certificate code.
        * @member {String} masked_gift_certificate_code
        */

        /**
        * The merchant ID.
        * @member {String} merchant_id
        */

        /**
        * The message.
        * @member {String} message
        */

        /**
        * The recipient email.
        * @member {String} recipient_email
        */

        /**
        * The recipient name.
        * @member {String} recipient_name
        */

        /**
        * The sender name.
        * @member {String} sender_name
        */

        /**
        * The gift certificate status.
        * @member {module:models/GiftCertificateModel.StatusEnum} status
        */


        /**
        * Allowed values for the <code>status</code> property.
        * @enum {String}
        * @readonly
        */

    }]);

    return GiftCertificateModel;
}();

GiftCertificateModel.StatusEnum = {

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "issued"
     * @const
     */
    "issued": "issued",

    /**
     * value: "partially_redeemed"
     * @const
     */
    "partially_redeemed": "partially_redeemed",

    /**
     * value: "redeemed"
     * @const
     */
    "redeemed": "redeemed"
};
exports.default = GiftCertificateModel;