'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */


var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _OrderPaymentCardRequestModel = require('./OrderPaymentCardRequestModel');

var _OrderPaymentCardRequestModel2 = _interopRequireDefault(_OrderPaymentCardRequestModel);

var _PaymentBankAccountRequestModel = require('./PaymentBankAccountRequestModel');

var _PaymentBankAccountRequestModel2 = _interopRequireDefault(_PaymentBankAccountRequestModel);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The OrderPaymentInstrumentRequestModel model module.
* @module models/OrderPaymentInstrumentRequestModel
* @version 17.8
*/
var OrderPaymentInstrumentRequestModel = function () {
    /**
    * Constructs a new <code>OrderPaymentInstrumentRequestModel</code>.
    * Document representing an order payment instrument request.
    * @alias module:models/OrderPaymentInstrumentRequestModel
    * @class
    */
    function OrderPaymentInstrumentRequestModel() {
        _classCallCheck(this, OrderPaymentInstrumentRequestModel);

        this.amount = undefined;
        this.bank_routing_number = undefined;
        this.create_customer_payment_instrument = undefined;
        this.customer_payment_instrument_id = undefined;
        this.gift_certificate_code = undefined;
        this.payment_bank_account = undefined;
        this.payment_card = undefined;
        this.payment_method_id = undefined;
    }

    /**
    * Constructs a <code>OrderPaymentInstrumentRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/OrderPaymentInstrumentRequestModel} obj Optional instance to populate.
    * @return {module:models/OrderPaymentInstrumentRequestModel} The populated <code>OrderPaymentInstrumentRequestModel</code> instance.
    */


    _createClass(OrderPaymentInstrumentRequestModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new OrderPaymentInstrumentRequestModel();

                if (data.hasOwnProperty('amount')) {
                    obj['amount'] = _ApiClient2.default.convertToType(data['amount'], 'Number');
                }
                if (data.hasOwnProperty('bank_routing_number')) {
                    obj['bank_routing_number'] = _ApiClient2.default.convertToType(data['bank_routing_number'], 'String');
                }
                if (data.hasOwnProperty('create_customer_payment_instrument')) {
                    obj['create_customer_payment_instrument'] = _ApiClient2.default.convertToType(data['create_customer_payment_instrument'], 'Boolean');
                }
                if (data.hasOwnProperty('customer_payment_instrument_id')) {
                    obj['customer_payment_instrument_id'] = _ApiClient2.default.convertToType(data['customer_payment_instrument_id'], 'String');
                }
                if (data.hasOwnProperty('gift_certificate_code')) {
                    obj['gift_certificate_code'] = _ApiClient2.default.convertToType(data['gift_certificate_code'], 'String');
                }
                if (data.hasOwnProperty('payment_bank_account')) {
                    obj['payment_bank_account'] = _PaymentBankAccountRequestModel2.default.constructFromObject(data['payment_bank_account']);
                }
                if (data.hasOwnProperty('payment_card')) {
                    obj['payment_card'] = _OrderPaymentCardRequestModel2.default.constructFromObject(data['payment_card']);
                }
                if (data.hasOwnProperty('payment_method_id')) {
                    obj['payment_method_id'] = _ApiClient2.default.convertToType(data['payment_method_id'], 'String');
                }
            }

            return obj;
        }

        /**
        * The payment transaction amount.
        * @member {Number} amount
        */

        /**
        * The bank routing number.
        * @member {String} bank_routing_number
        */

        /**
        * A flag indicating whether a related customer payment instrument should be created. The CustomerPaymentInstrument  is only created when the OrderPaymentInstrument was authorized successfully.
        * @member {Boolean} create_customer_payment_instrument
        */

        /**
        * The id of a customer payment instrument.
        * @member {String} customer_payment_instrument_id
        */

        /**
        * The gift certificate code.
        * @member {String} gift_certificate_code
        */

        /**
        * The payment bank account request data.
        * @member {module:models/PaymentBankAccountRequestModel} payment_bank_account
        */

        /**
        * The payment card.
        * @member {module:models/OrderPaymentCardRequestModel} payment_card
        */

        /**
        * The payment method id. Optional if a customer payment instrument id is specified.
        * @member {String} payment_method_id
        */

    }]);

    return OrderPaymentInstrumentRequestModel;
}();

exports.default = OrderPaymentInstrumentRequestModel;