'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */


var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _OrderModel = require('./OrderModel');

var _OrderModel2 = _interopRequireDefault(_OrderModel);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The OrderSearchHitModel model module.
* @module models/OrderSearchHitModel
* @version 17.8
*/
var OrderSearchHitModel = function () {
    /**
    * Constructs a new <code>OrderSearchHitModel</code>.
    * Document representing an order search hit.
    * @alias module:models/OrderSearchHitModel
    * @class
    */
    function OrderSearchHitModel() {
        _classCallCheck(this, OrderSearchHitModel);

        this.data = undefined;
        this.relevance = undefined;
    }

    /**
    * Constructs a <code>OrderSearchHitModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/OrderSearchHitModel} obj Optional instance to populate.
    * @return {module:models/OrderSearchHitModel} The populated <code>OrderSearchHitModel</code> instance.
    */


    _createClass(OrderSearchHitModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new OrderSearchHitModel();

                if (data.hasOwnProperty('data')) {
                    obj['data'] = _OrderModel2.default.constructFromObject(data['data']);
                }
                if (data.hasOwnProperty('relevance')) {
                    obj['relevance'] = _ApiClient2.default.convertToType(data['relevance'], 'Number');
                }
            }

            return obj;
        }

        /**
        *
        * @member {module:models/OrderModel} data
        */

        /**
        * The hit's relevance score.
        * @member {Number} relevance
        */

    }]);

    return OrderSearchHitModel;
}();

exports.default = OrderSearchHitModel;