'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */


var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The PaymentCardSpecModel model module.
* @module models/PaymentCardSpecModel
* @version 17.8
*/
var PaymentCardSpecModel = function () {
    /**
    * Constructs a new <code>PaymentCardSpecModel</code>.
    * Document representing the specification for a payment card.
    * @alias module:models/PaymentCardSpecModel
    * @class
    */
    function PaymentCardSpecModel() {
        _classCallCheck(this, PaymentCardSpecModel);

        this.card_type = undefined;
        this.checksum_verification_enabled = undefined;
        this.description = undefined;
        this.image = undefined;
        this.name = undefined;
        this.number_lengths = undefined;
        this.number_prefixes = undefined;
        this.security_code_length = undefined;
    }

    /**
    * Constructs a <code>PaymentCardSpecModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/PaymentCardSpecModel} obj Optional instance to populate.
    * @return {module:models/PaymentCardSpecModel} The populated <code>PaymentCardSpecModel</code> instance.
    */


    _createClass(PaymentCardSpecModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new PaymentCardSpecModel();

                if (data.hasOwnProperty('card_type')) {
                    obj['card_type'] = _ApiClient2.default.convertToType(data['card_type'], 'String');
                }
                if (data.hasOwnProperty('checksum_verification_enabled')) {
                    obj['checksum_verification_enabled'] = _ApiClient2.default.convertToType(data['checksum_verification_enabled'], 'Boolean');
                }
                if (data.hasOwnProperty('description')) {
                    obj['description'] = _ApiClient2.default.convertToType(data['description'], 'String');
                }
                if (data.hasOwnProperty('image')) {
                    obj['image'] = _ApiClient2.default.convertToType(data['image'], 'String');
                }
                if (data.hasOwnProperty('name')) {
                    obj['name'] = _ApiClient2.default.convertToType(data['name'], 'String');
                }
                if (data.hasOwnProperty('number_lengths')) {
                    obj['number_lengths'] = _ApiClient2.default.convertToType(data['number_lengths'], ['String']);
                }
                if (data.hasOwnProperty('number_prefixes')) {
                    obj['number_prefixes'] = _ApiClient2.default.convertToType(data['number_prefixes'], ['String']);
                }
                if (data.hasOwnProperty('security_code_length')) {
                    obj['security_code_length'] = _ApiClient2.default.convertToType(data['security_code_length'], 'Number');
                }
            }

            return obj;
        }

        /**
        * The type of the payment card.
        * @member {String} card_type
        */

        /**
        * A flag indicating whether the card number is verified using the Luhn checksum algorithm.
        * @member {Boolean} checksum_verification_enabled
        */

        /**
        * The localized description of the payment card.
        * @member {String} description
        */

        /**
        * The URL to the image that represents the payment card.
        * @member {String} image
        */

        /**
        * The localized name of the payment card.
        * @member {String} name
        */

        /**
        * The sorted list of number lengths (individual lengths as well as  length ranges).
        * @member {Array.<String>} number_lengths
        */

        /**
        * The sorted list of number prefixes (individual prefixes as well  as prefix ranges).
        * @member {Array.<String>} number_prefixes
        */

        /**
        * The length of the security code for this card.
        * @member {Number} security_code_length
        */

    }]);

    return PaymentCardSpecModel;
}();

exports.default = PaymentCardSpecModel;