'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The ProductListLinkModel model module.
* @module models/ProductListLinkModel
* @version 17.8
*/
var ProductListLinkModel = function () {
    /**
    * Constructs a new <code>ProductListLinkModel</code>.
    * Document representing a link to a product list.
    * @alias module:models/ProductListLinkModel
    * @class
    */

    function ProductListLinkModel() {
        _classCallCheck(this, ProductListLinkModel);

        this.description = undefined;
        this.link = undefined;
        this.name = undefined;
        this.public = undefined;
        this.title = undefined;
        this.type = undefined;
    }

    /**
    * Constructs a <code>ProductListLinkModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ProductListLinkModel} obj Optional instance to populate.
    * @return {module:models/ProductListLinkModel} The populated <code>ProductListLinkModel</code> instance.
    */


    _createClass(ProductListLinkModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new ProductListLinkModel();

                if (data.hasOwnProperty('description')) {
                    obj['description'] = _ApiClient2.default.convertToType(data['description'], 'String');
                }
                if (data.hasOwnProperty('link')) {
                    obj['link'] = _ApiClient2.default.convertToType(data['link'], 'String');
                }
                if (data.hasOwnProperty('name')) {
                    obj['name'] = _ApiClient2.default.convertToType(data['name'], 'String');
                }
                if (data.hasOwnProperty('public')) {
                    obj['public'] = _ApiClient2.default.convertToType(data['public'], 'Boolean');
                }
                if (data.hasOwnProperty('title')) {
                    obj['title'] = _ApiClient2.default.convertToType(data['title'], 'String');
                }
                if (data.hasOwnProperty('type')) {
                    obj['type'] = _ApiClient2.default.convertToType(data['type'], 'String');
                }
            }
            return obj;
        }

        /**
        * The description of this product list.
        * @member {String} description
        */

        /**
        * The target of the link.
        * @member {String} link
        */

        /**
        * The name of this product list.
        * @member {String} name
        */

        /**
        * A flag indicating whether the owner made this product list available for access  by other customers.
        * @member {Boolean} public
        */

        /**
        * The link title.
        * @member {String} title
        */

        /**
        * The type of the product list.
        * @member {module:models/ProductListLinkModel.TypeEnum} type
        */


        /**
        * Allowed values for the <code>type</code> property.
        * @enum {String}
        * @readonly
        */

    }]);

    return ProductListLinkModel;
}();

ProductListLinkModel.TypeEnum = {

    /**
     * value: "wish_list"
     * @const
     */
    "wish_list": "wish_list",

    /**
     * value: "gift_registry"
     * @const
     */
    "gift_registry": "gift_registry",

    /**
     * value: "shopping_list"
     * @const
     */
    "shopping_list": "shopping_list",

    /**
     * value: "custom_1"
     * @const
     */
    "custom_1": "custom_1",

    /**
     * value: "custom_2"
     * @const
     */
    "custom_2": "custom_2",

    /**
     * value: "custom_3"
     * @const
     */
    "custom_3": "custom_3"
};
exports.default = ProductListLinkModel;