'use strict'

Object.defineProperty(exports, '__esModule', {
    value: true
})

const _createClass = (function() { function defineProperties(target, props) { for (let i = 0; i < props.length; i++) { const descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ('value' in descriptor) { descriptor.writable = true } Object.defineProperty(target, descriptor.key, descriptor) } } return function(Constructor, protoProps, staticProps) { if (protoProps) { defineProperties(Constructor.prototype, protoProps) } if (staticProps) { defineProperties(Constructor, staticProps) } return Constructor } }()) /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */


const _ApiClient = require('../ApiClient')

const _ApiClient2 = _interopRequireDefault(_ApiClient)

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : {default: obj} }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function') } }

/**
* The ProductListShippingAddressModel model module.
* @module models/ProductListShippingAddressModel
* @version 17.8
*/
const ProductListShippingAddressModel = (function() {
    /**
    * Constructs a new <code>ProductListShippingAddressModel</code>.
    * Document representing a product list shipping address.
    * @alias module:models/ProductListShippingAddressModel
    * @class
    * @param addressId {String} The id of this address.
    */
    function ProductListShippingAddressModel(addressId) {
        _classCallCheck(this, ProductListShippingAddressModel)

        this.address_id = undefined
        this.city = undefined
        this.first_name = undefined
        this.last_name = undefined

        this.address_id = addressId
    }

    /**
    * Constructs a <code>ProductListShippingAddressModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ProductListShippingAddressModel} obj Optional instance to populate.
    * @return {module:models/ProductListShippingAddressModel} The populated <code>ProductListShippingAddressModel</code> instance.
    */


    _createClass(ProductListShippingAddressModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new ProductListShippingAddressModel()

                if (data.hasOwnProperty('address_id')) {
                    obj.address_id = _ApiClient2.default.convertToType(data.address_id, 'String')
                }
                if (data.hasOwnProperty('city')) {
                    obj.city = _ApiClient2.default.convertToType(data.city, 'String')
                }
                if (data.hasOwnProperty('first_name')) {
                    obj.first_name = _ApiClient2.default.convertToType(data.first_name, 'String')
                }
                if (data.hasOwnProperty('last_name')) {
                    obj.last_name = _ApiClient2.default.convertToType(data.last_name, 'String')
                }
            }

            return obj
        }

        /**
        * The id of this address.
        * @member {String} address_id
        */

        /**
        * The city of this address.
        * @member {String} city
        */

        /**
        * The first name of this address.
        * @member {String} first_name
        */

        /**
        * The last name of this address.
        * @member {String} last_name
        */

    }])

    return ProductListShippingAddressModel
}())

exports.default = ProductListShippingAddressModel
