'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */


var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The ShippingPromotionModel model module.
* @module models/ShippingPromotionModel
* @version 17.8
*/
var ShippingPromotionModel = function () {
    /**
    * Constructs a new <code>ShippingPromotionModel</code>.
    * Document representing a shipping promotion.
    * @alias module:models/ShippingPromotionModel
    * @class
    */
    function ShippingPromotionModel() {
        _classCallCheck(this, ShippingPromotionModel);

        this.callout_msg = undefined;
        this.link = undefined;
        this.promotion_id = undefined;
        this.promotion_name = undefined;
    }

    /**
    * Constructs a <code>ShippingPromotionModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ShippingPromotionModel} obj Optional instance to populate.
    * @return {module:models/ShippingPromotionModel} The populated <code>ShippingPromotionModel</code> instance.
    */


    _createClass(ShippingPromotionModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new ShippingPromotionModel();

                if (data.hasOwnProperty('callout_msg')) {
                    obj['callout_msg'] = _ApiClient2.default.convertToType(data['callout_msg'], 'String');
                }
                if (data.hasOwnProperty('link')) {
                    obj['link'] = _ApiClient2.default.convertToType(data['link'], 'String');
                }
                if (data.hasOwnProperty('promotion_id')) {
                    obj['promotion_id'] = _ApiClient2.default.convertToType(data['promotion_id'], 'String');
                }
                if (data.hasOwnProperty('promotion_name')) {
                    obj['promotion_name'] = _ApiClient2.default.convertToType(data['promotion_name'], 'String');
                }
            }

            return obj;
        }

        /**
        * The localized call-out message of the promotion.
        * @member {String} callout_msg
        */

        /**
        * The URL addressing the promotion.
        * @member {String} link
        */

        /**
        * The unique id of the promotion.
        * @member {String} promotion_id
        */

        /**
        * The localized promotion name.
        * @member {String} promotion_name
        */

    }]);

    return ShippingPromotionModel;
}();

exports.default = ShippingPromotionModel;