'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */


var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _SuggestedTermModel = require('./SuggestedTermModel');

var _SuggestedTermModel2 = _interopRequireDefault(_SuggestedTermModel);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The SuggestedTermsModel model module.
* @module models/SuggestedTermsModel
* @version 17.8
*/
var SuggestedTermsModel = function () {
    /**
    * Constructs a new <code>SuggestedTermsModel</code>.
    * Document representing a list of suggested terms for each term of a search phrase.
    * @alias module:models/SuggestedTermsModel
    * @class
    */
    function SuggestedTermsModel() {
        _classCallCheck(this, SuggestedTermsModel);

        this.original_term = undefined;
        this.terms = undefined;
    }

    /**
    * Constructs a <code>SuggestedTermsModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/SuggestedTermsModel} obj Optional instance to populate.
    * @return {module:models/SuggestedTermsModel} The populated <code>SuggestedTermsModel</code> instance.
    */


    _createClass(SuggestedTermsModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new SuggestedTermsModel();

                if (data.hasOwnProperty('original_term')) {
                    obj['original_term'] = _ApiClient2.default.convertToType(data['original_term'], 'String');
                }
                if (data.hasOwnProperty('terms')) {
                    obj['terms'] = _ApiClient2.default.convertToType(data['terms'], [_SuggestedTermModel2.default]);
                }
            }

            return obj;
        }

        /**
        * Returns the original term that the suggested terms relates to.
        * @member {String} original_term
        */

        /**
        * Returns the suggested terms.
        * @member {Array.<module:models/SuggestedTermModel>} terms
        */

    }]);

    return SuggestedTermsModel;
}();

exports.default = SuggestedTermsModel;