'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The TermFilterModel model module.
* @module models/TermFilterModel
* @version 17.8
*/
var TermFilterModel = function () {
    /**
    * Constructs a new <code>TermFilterModel</code>.
    * Document representing a term filter.  
    * @alias module:models/TermFilterModel
    * @class
    * @param field {String} The filter field.
    * @param operator {module:models/TermFilterModel.OperatorEnum} The operator to compare the field's values with the given ones.
    */

    function TermFilterModel(field, operator) {
        _classCallCheck(this, TermFilterModel);

        this.field = undefined;
        this.operator = undefined;
        this.values = undefined;


        this['field'] = field;this['operator'] = operator;
    }

    /**
    * Constructs a <code>TermFilterModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/TermFilterModel} obj Optional instance to populate.
    * @return {module:models/TermFilterModel} The populated <code>TermFilterModel</code> instance.
    */


    _createClass(TermFilterModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new TermFilterModel();

                if (data.hasOwnProperty('field')) {
                    obj['field'] = _ApiClient2.default.convertToType(data['field'], 'String');
                }
                if (data.hasOwnProperty('operator')) {
                    obj['operator'] = _ApiClient2.default.convertToType(data['operator'], 'String');
                }
                if (data.hasOwnProperty('values')) {
                    obj['values'] = _ApiClient2.default.convertToType(data['values'], [Object]);
                }
            }
            return obj;
        }

        /**
        * The filter field.
        * @member {String} field
        */

        /**
        * The operator to compare the field's values with the given ones.
        * @member {module:models/TermFilterModel.OperatorEnum} operator
        */

        /**
        * The filter values.
        * @member {Array.<Object>} values
        */


        /**
        * Allowed values for the <code>operator</code> property.
        * @enum {String}
        * @readonly
        */

    }]);

    return TermFilterModel;
}();

TermFilterModel.OperatorEnum = {

    /**
     * value: "is"
     * @const
     */
    "is": "is",

    /**
     * value: "one_of"
     * @const
     */
    "one_of": "one_of",

    /**
     * value: "is_null"
     * @const
     */
    "is_null": "is_null",

    /**
     * value: "is_not_null"
     * @const
     */
    "is_not_null": "is_not_null",

    /**
     * value: "less"
     * @const
     */
    "less": "less",

    /**
     * value: "greater"
     * @const
     */
    "greater": "greater",

    /**
     * value: "not_in"
     * @const
     */
    "not_in": "not_in",

    /**
     * value: "neq"
     * @const
     */
    "neq": "neq"
};
exports.default = TermFilterModel;