'use strict'

Object.defineProperty(exports, '__esModule', {
    value: true
})

const _createClass = (function() { function defineProperties(target, props) { for (let i = 0; i < props.length; i++) { const descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ('value' in descriptor) { descriptor.writable = true } Object.defineProperty(target, descriptor.key, descriptor) } } return function(Constructor, protoProps, staticProps) { if (protoProps) { defineProperties(Constructor.prototype, protoProps) } if (staticProps) { defineProperties(Constructor, staticProps) } return Constructor } }()) /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Shop API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 17.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */


const _ApiClient = require('../ApiClient')

const _ApiClient2 = _interopRequireDefault(_ApiClient)

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : {default: obj} }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function') } }

/**
* The VariationAttributeValueModel model module.
* @module models/VariationAttributeValueModel
* @version 17.8
*/
const VariationAttributeValueModel = (function() {
    /**
    * Constructs a new <code>VariationAttributeValueModel</code>.
    * @alias module:models/VariationAttributeValueModel
    * @class
    * @param value {String}
    */
    function VariationAttributeValueModel(value) {
        _classCallCheck(this, VariationAttributeValueModel)

        this.description = undefined
        this.name = undefined
        this.orderable = undefined
        this.value = undefined

        this.value = value
    }

    /**
    * Constructs a <code>VariationAttributeValueModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/VariationAttributeValueModel} obj Optional instance to populate.
    * @return {module:models/VariationAttributeValueModel} The populated <code>VariationAttributeValueModel</code> instance.
    */


    _createClass(VariationAttributeValueModel, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new VariationAttributeValueModel()

                if (data.hasOwnProperty('description')) {
                    obj.description = _ApiClient2.default.convertToType(data.description, 'String')
                }
                if (data.hasOwnProperty('name')) {
                    obj.name = _ApiClient2.default.convertToType(data.name, 'String')
                }
                if (data.hasOwnProperty('orderable')) {
                    obj.orderable = _ApiClient2.default.convertToType(data.orderable, 'Boolean')
                }
                if (data.hasOwnProperty('value')) {
                    obj.value = _ApiClient2.default.convertToType(data.value, 'String')
                }
            }
            return obj
        }

        /**
        * @member {String} description
        */

        /**
        * @member {String} name
        */

        /**
        * @member {Boolean} orderable
        */

        /**
        * @member {String} value
        */

    }])

    return VariationAttributeValueModel
}())

exports.default = VariationAttributeValueModel
