/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
    // AMD.
        define(['expect.js', '../../src/index'], factory)
    } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'))
    } else {
    // Browser globals (root is window)
        factory(root.expect, root.ShopApi)
    }
}(this, (expect, ShopApi) => {
    'use strict'

    let instance

    beforeEach(() => {
        instance = new ShopApi.CouponItemModel()
    })

    const getProperty = (object, getter, property) => {
    // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function') { return object[getter]() } else { return object[property] }
    }

    const setProperty = (object, setter, property, value) => {
    // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function') { object[setter](value) } else { object[property] = value }
    }

    describe('CouponItemModel', () => {
        it('should create an instance of CouponItemModel', () => {
      // uncomment below and update the code to test CouponItemModel
      // var instane = new ShopApi.CouponItemModel()
      // expect(instance).to.be.a(ShopApi.CouponItemModel);
        })

        it('should have the property code (base name: "code")', () => {
      // uncomment below and update the code to test the property code
      // var instane = new ShopApi.CouponItemModel()
      // expect(instance).to.be();
        })

        it('should have the property couponItemId (base name: "coupon_item_id")', () => {
      // uncomment below and update the code to test the property couponItemId
      // var instane = new ShopApi.CouponItemModel()
      // expect(instance).to.be();
        })

        it('should have the property statusCode (base name: "status_code")', () => {
      // uncomment below and update the code to test the property statusCode
      // var instane = new ShopApi.CouponItemModel()
      // expect(instance).to.be();
        })

        it('should have the property valid (base name: "valid")', () => {
      // uncomment below and update the code to test the property valid
      // var instane = new ShopApi.CouponItemModel()
      // expect(instance).to.be();
        })

    })

}))
