/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2020 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import expect from 'expect.js'
import ShopApi from '../../src/index'

let instance

beforeEach(() => {
    instance = new ShopApi.ProductListEvent()
})

const getProperty = (object, getter, property) => {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') {
        return object[getter]()
    } else {
        return object[property]
    }
}

const setProperty = (object, setter, property, value) => {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') {
        object[setter](value)
    } else {
        object[property] = value
    }
}

describe('ProductListEventModel', () => {
    it('should create an instance of ProductListEventModel', () => {
        // uncomment below and update the code to test ProductListEventModel
        // var instane = new ShopApi.ProductListEvent()
        // expect(instance).to.be.a(ShopApi.ProductListEvent);
    })

    it('should have the property city (base name: "city")', () => {
        // uncomment below and update the code to test the property city
        // var instane = new ShopApi.ProductListEvent()
        // expect(instance).to.be();
    })

    it('should have the property country (base name: "country")', () => {
        // uncomment below and update the code to test the property country
        // var instane = new ShopApi.ProductListEvent()
        // expect(instance).to.be();
    })

    it('should have the property _date (base name: "date")', () => {
        // uncomment below and update the code to test the property _date
        // var instane = new ShopApi.ProductListEvent()
        // expect(instance).to.be();
    })

    it('should have the property state (base name: "state")', () => {
        // uncomment below and update the code to test the property state
        // var instane = new ShopApi.ProductListEvent()
        // expect(instance).to.be();
    })

    it('should have the property type (base name: "type")', () => {
        // uncomment below and update the code to test the property type
        // var instane = new ShopApi.ProductListEvent()
        // expect(instance).to.be();
    })

})
