/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2020 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import expect from 'expect.js'
import ShopApi from '../../src/index'

let instance

beforeEach(() => {
    instance = new ShopApi.ShippingMethod()
})

const getProperty = (object, getter, property) => {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') {
        return object[getter]()
    } else {
        return object[property]
    }
}

const setProperty = (object, setter, property, value) => {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') {
        object[setter](value)
    } else {
        object[property] = value
    }
}

describe('ShippingMethodModel', () => {
    it('should create an instance of ShippingMethodModel', () => {
        // uncomment below and update the code to test ShippingMethodModel
        // var instane = new ShopApi.ShippingMethod()
        // expect(instance).to.be.a(ShopApi.ShippingMethod);
    })

    it('should have the property cStorePickupEnabled (base name: "c_storePickupEnabled")', () => {
        // uncomment below and update the code to test the property cStorePickupEnabled
        // var instane = new ShopApi.ShippingMethod()
        // expect(instance).to.be();
    })

    it('should have the property description (base name: "description")', () => {
        // uncomment below and update the code to test the property description
        // var instane = new ShopApi.ShippingMethod()
        // expect(instance).to.be();
    })

    it('should have the property externalShippingMethod (base name: "external_shipping_method")', () => {
        // uncomment below and update the code to test the property externalShippingMethod
        // var instane = new ShopApi.ShippingMethod()
        // expect(instance).to.be();
    })

    it('should have the property id (base name: "id")', () => {
        // uncomment below and update the code to test the property id
        // var instane = new ShopApi.ShippingMethod()
        // expect(instance).to.be();
    })

    it('should have the property name (base name: "name")', () => {
        // uncomment below and update the code to test the property name
        // var instane = new ShopApi.ShippingMethod()
        // expect(instance).to.be();
    })

    it('should have the property price (base name: "price")', () => {
        // uncomment below and update the code to test the property price
        // var instane = new ShopApi.ShippingMethod()
        // expect(instance).to.be();
    })

    it('should have the property shippingPromotions (base name: "shipping_promotions")', () => {
        // uncomment below and update the code to test the property shippingPromotions
        // var instane = new ShopApi.ShippingMethod()
        // expect(instance).to.be();
    })

})
