/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2020 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient'
import ApproachingDiscount from './ApproachingDiscount'





/**
* The ApproachingDiscountResult model module.
* @module models/ApproachingDiscountResult
* @version 20.4
*/
export default class ApproachingDiscountResult {
    /**
    * Constructs a new <code>ApproachingDiscountResult</code>.
    * A result of a approaching discount request.
    * @alias module:models/ApproachingDiscountResult
    * @class
    */

    constructor() {








    }

    /**
    * Constructs a <code>ApproachingDiscountResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ApproachingDiscountResult} obj Optional instance to populate.
    * @return {module:models/ApproachingDiscountResult} The populated <code>ApproachingDiscountResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApproachingDiscountResult()





            if (data.hasOwnProperty('approaching_discounts')) {
                obj.approaching_discounts = ApiClient.convertToType(data.approaching_discounts, [ApproachingDiscount])
            }
        }
        return obj
    }

    /**
    * Lists approaching discounts.
    * @member {Array.<module:models/ApproachingDiscount>} approaching_discounts
    */
    approaching_discounts = undefined;








}


