/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient'

/**
* The ContentFolderModel model module.
* @module models/ContentFolderModel
* @version 17.8
*/
export default class ContentFolderModel {
    /**
    * Constructs a new <code>ContentFolderModel</code>.
    * Document representing a content folder.
    * @alias module:models/ContentFolderModel
    * @class
    * @param id {String} The id of the content folder.
    */

    constructor(id) {
        this['id'] = id;
    }

    /**
    * Constructs a <code>ContentFolderModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ContentFolderModel} obj Optional instance to populate.
    * @return {module:models/ContentFolderModel} The populated <code>ContentFolderModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContentFolderModel()

            if (data.hasOwnProperty('c_customCSSFile')) {
                obj['c_customCSSFile'] = ApiClient.convertToType(data['c_customCSSFile'], 'String')
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String')
            }
            if (data.hasOwnProperty('folders')) {
                obj['folders'] = ApiClient.convertToType(data['folders'], [ContentFolderModel]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String')
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String')
            }
            if (data.hasOwnProperty('page_description')) {
                obj['page_description'] = ApiClient.convertToType(data['page_description'], 'String')
            }
            if (data.hasOwnProperty('page_keywords')) {
                obj['page_keywords'] = ApiClient.convertToType(data['page_keywords'], 'String')
            }
            if (data.hasOwnProperty('page_title')) {
                obj['page_title'] = ApiClient.convertToType(data['page_title'], 'String')
            }
            if (data.hasOwnProperty('parent_folder_id')) {
                obj['parent_folder_id'] = ApiClient.convertToType(data['parent_folder_id'], 'String')
            }
        }
        return obj;
    }

    /**
    * Use this attribute to apply custom styles for this category.
    * @member {String} c_customCSSFile
    */
    c_customCSSFile = undefined
    /**
    * The localized content folder description.
    * @member {String} description
    */
    description = undefined
    /**
    * The array of content subfolders. This array can be empty.
    * @member {Array.<module:models/ContentFolderModel>} folders
    */
    folders = undefined
    /**
    * The id of the content folder.
    * @member {String} id
    */
    id = undefined
    /**
    * The localized content folder name.
    * @member {String} name
    */
    name = undefined
    /**
    * The localized content folder page description.
    * @member {String} page_description
    */
    page_description = undefined
    /**
    * The localized content folder page description.
    * @member {String} page_keywords
    */
    page_keywords = undefined
    /**
    * The localized content folder page title.
    * @member {String} page_title
    */
    page_title = undefined
    /**
    * The id of the parent content folder.
    * @member {String} parent_folder_id
    */
    parent_folder_id = undefined
}
