/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient'
import ContentFolderModel from './ContentFolderModel'

/**
* The ContentFolderResultModel model module.
* @module models/ContentFolderResultModel
* @version 17.8
*/
export default class ContentFolderResultModel {
    /**
    * Constructs a new <code>ContentFolderResultModel</code>.
    * Result document containing an array of content folders.
    * @alias module:models/ContentFolderResultModel
    * @class
    */
    constructor() {}

    /**
    * Constructs a <code>ContentFolderResultModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ContentFolderResultModel} obj Optional instance to populate.
    * @return {module:models/ContentFolderResultModel} The populated <code>ContentFolderResultModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContentFolderResultModel()

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number')
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [ContentFolderModel]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number')
            }
        }

        return obj
    }

    /**
    * The number of returned documents.
    * @member {Number} count
    */
    count = undefined
    /**
    * The array of content folder documents.
    * @member {Array.<module:models/ContentFolderModel>} data
    */
    data = undefined
    /**
    * The total number of documents.
    * @member {Number} total
    */
    total = undefined
}
