/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient'
import CustomerProductListItemModel from './CustomerProductListItemModel'





/**
* The CustomerProductListItemResultModel model module.
* @module models/CustomerProductListItemResultModel
* @version 17.8
*/
export default class CustomerProductListItemResultModel {
    /**
    * Constructs a new <code>CustomerProductListItemResultModel</code>.
    * Document representing a customer product list items result.
    * @alias module:models/CustomerProductListItemResultModel
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CustomerProductListItemResultModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CustomerProductListItemResultModel} obj Optional instance to populate.
    * @return {module:models/CustomerProductListItemResultModel} The populated <code>CustomerProductListItemResultModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerProductListItemResultModel()

            
            
            

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number')
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [CustomerProductListItemModel]);
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String')
            }
            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String')
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Number')
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number')
            }
        }
        return obj;
    }

    /**
    * @member {Number} count
    */
    count = undefined
    /**
    * The customer product list items.
    * @member {Array.<module:models/CustomerProductListItemModel>} data
    */
    data = undefined
    /**
    * The URL of the next result page.
    * @member {String} next
    */
    next = undefined
    /**
    * The URL of the previous result page.
    * @member {String} previous
    */
    previous = undefined
    /**
    * The zero-based index of the first search hit to include in the result.
    * @member {Number} start
    */
    start = undefined
    /**
    * @member {Number} total
    */
    total = undefined








}


