/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2020 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient'





/**
* The CustomerProductListItemPurchase model module.
* @module models/CustomerProductListItemPurchase
* @version 20.4
*/
export default class CustomerProductListItemPurchase {
    /**
    * Constructs a new <code>CustomerProductListItemPurchase</code>.
    * Document representing a customer product list item purchase.
    * @alias module:models/CustomerProductListItemPurchase
    * @class
    */

    constructor() {








    }

    /**
    * Constructs a <code>CustomerProductListItemPurchase</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CustomerProductListItemPurchase} obj Optional instance to populate.
    * @return {module:models/CustomerProductListItemPurchase} The populated <code>CustomerProductListItemPurchase</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerProductListItemPurchase()





            if (data.hasOwnProperty('id')) {
                obj.id = ApiClient.convertToType(data.id, 'String')
            }
            if (data.hasOwnProperty('order_no')) {
                obj.order_no = ApiClient.convertToType(data.order_no, 'String')
            }
            if (data.hasOwnProperty('product_list_item_id')) {
                obj.product_list_item_id = ApiClient.convertToType(data.product_list_item_id, 'String')
            }
            if (data.hasOwnProperty('purchaser_name')) {
                obj.purchaser_name = ApiClient.convertToType(data.purchaser_name, 'String')
            }
            if (data.hasOwnProperty('quantity')) {
                obj.quantity = ApiClient.convertToType(data.quantity, 'Number')
            }
        }
        return obj
    }

    /**
    * The id of this purchase.
    * @member {String} id
    */
    id = undefined;
    /**
    * The order number of this purchase.
    * @member {String} order_no
    */
    order_no = undefined;
    /**
    * The id of the product list item this purchase relates to.
    * @member {String} product_list_item_id
    */
    product_list_item_id = undefined;
    /**
    * The name of the purchaser.
    * @member {String} purchaser_name
    */
    purchaser_name = undefined;
    /**
    * The quantity of this product list item purchased.
    * @member {Number} quantity
    */
    quantity = undefined;








}


