/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2020 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient'
import CustomerProductListItemPurchase from './CustomerProductListItemPurchase'





/**
* The CustomerProductListItemPurchaseResult model module.
* @module models/CustomerProductListItemPurchaseResult
* @version 20.4
*/
export default class CustomerProductListItemPurchaseResult {
    /**
    * Constructs a new <code>CustomerProductListItemPurchaseResult</code>.
    * Document representing a customer product list purchases result.
    * @alias module:models/CustomerProductListItemPurchaseResult
    * @class
    */

    constructor() {








    }

    /**
    * Constructs a <code>CustomerProductListItemPurchaseResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CustomerProductListItemPurchaseResult} obj Optional instance to populate.
    * @return {module:models/CustomerProductListItemPurchaseResult} The populated <code>CustomerProductListItemPurchaseResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerProductListItemPurchaseResult()





            if (data.hasOwnProperty('count')) {
                obj.count = ApiClient.convertToType(data.count, 'Number')
            }
            if (data.hasOwnProperty('data')) {
                obj.data = ApiClient.convertToType(data.data, [CustomerProductListItemPurchase])
            }
            if (data.hasOwnProperty('total')) {
                obj.total = ApiClient.convertToType(data.total, 'Number')
            }
        }
        return obj
    }

    /**
    * The number of returned documents.
    * @member {Number} count
    */
    count = undefined;
    /**
    * The customer product list item purchases.
    * @member {Array.<module:models/CustomerProductListItemPurchase>} data
    */
    data = undefined;
    /**
    * The total number of documents.
    * @member {Number} total
    */
    total = undefined;








}


