/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2020 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient'





/**
* The GiftCertificateRequest model module.
* @module models/GiftCertificateRequest
* @version 20.4
*/
export default class GiftCertificateRequest {
    /**
    * Constructs a new <code>GiftCertificateRequest</code>.
    * Document representing a gift certificate request data.
    * @alias module:models/GiftCertificateRequest
    * @class
    */

    constructor() {








    }

    /**
    * Constructs a <code>GiftCertificateRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/GiftCertificateRequest} obj Optional instance to populate.
    * @return {module:models/GiftCertificateRequest} The populated <code>GiftCertificateRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GiftCertificateRequest()





            if (data.hasOwnProperty('gift_certificate_code')) {
                obj.gift_certificate_code = ApiClient.convertToType(data.gift_certificate_code, 'String')
            }
        }
        return obj
    }

    /**
    * The gift certificate code.
    * @member {String} gift_certificate_code
    */
    gift_certificate_code = undefined;








}


