/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2020 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/* eslint-disable dot-notation */
/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient'

/**
* The Note model module.
* @module models/Note
* @version 17.8
*/
export default class Note {
    /**
    * Constructs a new <code>Note</code>.
    * Document representing a note to an object.
    * @alias module:models/Note
    * @class
    */
    constructor() {
        /**
        * The author of the note.
        * @member {String} created_by
        */
        this.created_by = undefined

        /**
        * The creation date of the note.
        * @member {Date} creation_date
        */
        this.creation_date = undefined

        /**
        * The ID of the note.
        * @member {String} id
        */
        this.id = undefined

        /**
        * The note's subject.
        * @member {String} subject
        */
        this.subject = undefined

        /**
        * The note's text.
        * @member {String} text
        */
        this.text = undefined
    }

    /**
    * Constructs a <code>Note</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/Note} obj Optional instance to populate.
    * @return {module:models/Note} The populated <code>Note</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Note()

            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'String')
            }
            if (data.hasOwnProperty('creation_date')) {
                obj['creation_date'] = ApiClient.convertToType(data['creation_date'], 'Date')
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String')
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String')
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String')
            }
        }

        return obj
    }
}
