/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient'
import PaymentCardSpecModel from './PaymentCardSpecModel'





/**
* The PaymentMethodModel model module.
* @module models/PaymentMethodModel
* @version 17.8
*/
export default class PaymentMethodModel {
    /**
    * Constructs a new <code>PaymentMethodModel</code>.
    * Document representing a payment method.
    * @alias module:models/PaymentMethodModel
    * @class
    * @param id {String} The id of the payment method or card.
    */

    constructor(id) {
        

        
        

        this['id'] = id;

        
    }

    /**
    * Constructs a <code>PaymentMethodModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/PaymentMethodModel} obj Optional instance to populate.
    * @return {module:models/PaymentMethodModel} The populated <code>PaymentMethodModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentMethodModel()

            
            
            

            if (data.hasOwnProperty('cards')) {
                obj['cards'] = ApiClient.convertToType(data['cards'], [PaymentCardSpecModel]);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String')
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String')
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String')
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String')
            }
        }
        return obj
    }

    /**
    * The sorted array of payment cards (included only when the system payment method is CREDIT_CARD).
    * @member {Array.<module:models/PaymentCardSpecModel>} cards
    */
    cards = undefined
    /**
    * The localized description of the payment method or card.
    * @member {String} description
    */
    description = undefined
    /**
    * The id of the payment method or card.
    * @member {String} id
    */
    id = undefined
    /**
    * The URL to the image that represents the payment method or card.
    * @member {String} image
    */
    image = undefined
    /**
    * The localized name of the payment method or card.
    * @member {String} name
    */
    name = undefined








}


