/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/* eslint-disable dot-notation */
/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient'

/**
* The ProductSearchSortingOption model module.
* @module models/ProductSearchSortingOption
* @version 17.8
*/
export default class ProductSearchSortingOption {
    /**
    * Constructs a new <code>ProductSearchSortingOption</code>.
    * Document representing a product search sorting option.
    * @alias module:models/ProductSearchSortingOption
    * @class
    */
    constructor() {
        /**
        * The id of the sorting option.
        * @member {String} id
        */
        this.id = undefined

        /**
        * The localized label of the sorting option.
        * @member {String} label
        */
        this.label = undefined
    }

    /**
    * Constructs a <code>ProductSearchSortingOption</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ProductSearchSortingOption} obj Optional instance to populate.
    * @return {module:models/ProductSearchSortingOption} The populated <code>ProductSearchSortingOption</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductSearchSortingOption()

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String')
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String')
            }
        }

        return obj
    }
}
