/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2020 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/* eslint-disable dot-notation */
/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient'

/**
* The ProductSimpleLink model module.
* @module models/ProductSimpleLink
* @version 17.8
*/
export default class ProductSimpleLink {
    /**
    * Constructs a new <code>ProductSimpleLink</code>.
    * Document representing a link to a product.
    * @alias module:models/ProductSimpleLink
    * @class
    */
    constructor() {
        /**
        * The target of the link.
        * @member {String} link
        */
        this.link = undefined

        /**
        * The link title.
        * @member {String} title
        */
        this.title = undefined
    }

    /**
    * Constructs a <code>ProductSimpleLink</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ProductSimpleLink} obj Optional instance to populate.
    * @return {module:models/ProductSimpleLink} The populated <code>ProductSimpleLink</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductSimpleLink()

            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String')
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String')
            }
        }

        return obj
    }
}
