/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/* eslint-disable dot-notation */
/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient'

/**
* The ResultPage model module.
* @module models/ResultPage
* @version 17.8
*/
export default class ResultPage {
    /**
    * Constructs a new <code>ResultPage</code>.
    * Data that can be used to get the next and previous page of a Data API results object.
    * @alias module:models/ResultPage
    * @class
    */
    constructor() {
        /**
        * Returns the count of search hits to include in the page.
        * @member {Number} count
        */
        this.count = undefined

        /**
        * Returns the zero-based index of the first search hit in the page.
        * @member {Number} start
        */
        this.start = undefined
    }

    /**
    * Constructs a <code>ResultPage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ResultPage} obj Optional instance to populate.
    * @return {module:models/ResultPage} The populated <code>ResultPage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResultPage()

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number')
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Number')
            }
        }

        return obj
    }
}
