/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient'

/**
* The SuggestedTermModel model module.
* @module models/SuggestedTermModel
* @version 17.8
*/
export default class SuggestedTermModel {
    /**
    * Constructs a new <code>SuggestedTermModel</code>.
    * Document representing a suggested term.
    * @alias module:models/SuggestedTermModel
    * @class
    */
    constructor() {}

    /**
    * Constructs a <code>SuggestedTermModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/SuggestedTermModel} obj Optional instance to populate.
    * @return {module:models/SuggestedTermModel} The populated <code>SuggestedTermModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SuggestedTermModel()

            if (data.hasOwnProperty('completed')) {
                obj['completed'] = ApiClient.convertToType(data['completed'], 'Boolean')
            }
            if (data.hasOwnProperty('corrected')) {
                obj['corrected'] = ApiClient.convertToType(data['corrected'], 'Boolean')
            }
            if (data.hasOwnProperty('exact_match')) {
                obj['exact_match'] = ApiClient.convertToType(data['exact_match'], 'Boolean')
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String')
            }
        }

        return obj
    }

    /**
    * Returns whether this term value is a completion match.
    * @member {Boolean} completed
    */
    completed = undefined
    /**
    * Returns whether this term value is a correction match.
    * @member {Boolean} corrected
    */
    corrected = undefined
    /**
    * Returns whether this term value is a exact match.
    * @member {Boolean} exact_match
    */
    exact_match = undefined
    /**
    * Returns the term value.
    * @member {String} value
    */
    value = undefined
}
