/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', '../../src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.ShopApi);
    }
}(this, function(expect, ShopApi) {
    'use strict'

    var instance;

    beforeEach(function() {
        instance = new ShopApi.ProductSearchApi()

        const defaultClient = ShopApi.ApiClient.instance
        defaultClient.defaultHeaders = {
            'x-dw-client-id': '5640cc6b-f5e9-466e-9134-9853e9f9db93'
        }
        defaultClient.basePath = 'https://thingproxy.freeboard.io/fetch/https://mobify-tech-prtnr-na03-dw.demandware.net/s/2017refresh/dw/shop/v17_8'.replace(/\/+$/, '')
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('ProductSearchApi', function() {
        //
        describe('getProductSearch', () => {
            it('should call getProductSearch successfully', () =>
                instance.getProductSearch({})
                    .then((productSearchResult) => {
                        expect(productSearchResult.constructor.name).to.be('ProductSearchResultModel')
                    })
                    .catch((error) => {
                        throw error
                    })
            )
        })

        describe('getProductSearch', () => {
            it('should call getProductSearch for all products in root successfully', () =>
                instance.getProductSearch({refine: ['cgid=root']})
                    .then((productSearchResult) => {
                        expect(productSearchResult.count).to.above(0)
                    })
                    .catch((error) => {
                        throw error
                    })
            )
        })

        describe('getProductSearchAvailability', () => {
            it('should call getProductSearchAvailability successfully', () =>
                instance.getProductSearchAvailability({refine: ['cgid=root'], count: 1})
                    .then((productSearchResult) => {
                        expect(productSearchResult.constructor.name).to.be('ProductSearchResultModel')
                        expect(productSearchResult.hits[0].orderable).not.to.be(undefined)
                    })
                    .catch((error) => {
                        throw error
                    })
            )
        })

        describe('getProductSearchImages', () => {
            it('should call getProductSearchImages successfully', () =>
                instance.getProductSearchImages({refine: ['cgid=root'], count: 1})
                    .then((productSearchResult) => {
                        expect(productSearchResult.constructor.name).to.be('ProductSearchResultModel')
                        expect(productSearchResult.hits[0].image).to.be.an('object')
                    })
                    .catch((error) => {
                        throw error
                    })
            )
        })

        describe('getProductSearchPrices', () => {
            it('should call getProductSearchPrices successfully', () =>
                instance.getProductSearchPrices({refine: ['cgid=root'], count: 1})
                    .then((productSearchResult) => {
                        expect(productSearchResult.constructor.name).to.be('ProductSearchResultModel')
                        expect(productSearchResult.hits[0].price).not.to.be(undefined)
                    })
                    .catch((error) => {
                        throw error
                    })
            )
        })

        describe('getProductSearchVariations', () => {
            it('should call getProductSearchVariations successfully', () =>
                instance.getProductSearchVariations({refine: ['cgid=root'], count: 1})
                    .then((productSearchResult) => {
                        expect(productSearchResult.constructor.name).to.be('ProductSearchResultModel')
                        expect(productSearchResult.hits[0].variation_attributes).to.be.an('object')
                    })
                    .catch((error) => {
                        throw error
                    })
            )
        });

    })

}))
